# src/services/render_utils.py
from xml.etree import ElementTree as ET
from typing import Optional
import html

def mathml_to_text(mathml: str) -> str:
    """
    Convert simple presentation MathML to a readable plain-text string.
    This is a best-effort converter for small expressions and MathML generated by the model.
    It:
      - handles MathML wrapped in <p> tags or direct MathML
      - extracts text from <mtext>, <mn>, <mi>, <mo> in document order,
      - treats <mo>&#160;</mo> and other space operators as spaces,
      - joins them with a space, and collapses multiple spaces.
    If XML parsing fails, fallback to stripping tags naively.
    """
    if not mathml:
        return ""
    try:
        root = ET.fromstring(mathml)
        # If wrapped in <p> tag, find the math element
        if root.tag == 'p':
            # Find math element (handle namespaces)
            math_elem = None
            for elem in root.iter():
                if elem.tag.endswith('math') or elem.tag == 'math' or '{http://www.w3.org/1998/Math/MathML}math' in elem.tag:
                    math_elem = elem
                    break
            if math_elem is None:
                # Fallback: use the root's children
                math_elem = root
            root = math_elem
    except Exception:
        # naive fallback: remove tags
        s = mathml
        # replace closing tags with space
        import re
        s = re.sub(r"<[^>]+>", " ", s)
        s = html.unescape(s)
        s = " ".join(s.split())
        return s

    parts = []

    def walk(node):
        # Extract direct text content from the node
        if node.text:
            # XML parser decodes entities like &#160; to actual characters
            # Extract text and handle non-breaking spaces and regular spaces
            text_content = node.text
            # Replace non-breaking spaces with regular spaces for readability
            text_content = text_content.replace('\u00A0', ' ')
            if text_content.strip():
                parts.append(text_content.strip())
            elif ' ' in text_content or '\u00A0' in text_content:
                # If it's just whitespace, add a space
                parts.append(' ')
        # Walk through all children recursively
        for ch in node:
            walk(ch)
        # Handle tail text (text that appears after this element's closing tag)
        if node.tail:
            tail_content = node.tail.replace('\u00A0', ' ')
            if tail_content.strip():
                parts.append(tail_content.strip())
            elif ' ' in tail_content or '\u00A0' in tail_content:
                parts.append(' ')

    walk(root)
    # Join all parts with spaces
    text = " ".join(parts)
    # Collapse multiple consecutive spaces to single spaces
    text = " ".join(text.split())
    # unescape any remaining HTML entities
    return html.unescape(text)

def render_mathml_html(mathml: str, width: int = 700) -> str:
    """
    Return a complete HTML snippet that renders the MathML properly.
    Use this with st.components.v1.html(...).
    """
    safe_mathml = html.escape(mathml).replace("&lt;", "<").replace("&gt;", ">")
    html_code = f"""
    <html>
      <head>
        <meta charset="utf-8"/>
        <style>
          body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial; margin: 0; padding: 6px; }}
          .qcard {{ border-radius: 8px; padding: 12px; box-shadow: 0 1px 4px rgba(0,0,0,0.08); background: #fff; }}
          .math {{ font-size: 20px; }}
          .label {{ color: #555; font-size: 13px; margin-bottom: 6px; }}
          .option {{ margin: 6px 0; }}
        </style>
      </head>
      <body>
        <div class="qcard">
          <div class="math">
            {mathml}
          </div>
        </div>
      </body>
    </html>
    """
    return html_code
